# Generated by Django 5.0.6 on 2024-06-22 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_purchasedetail_purchasereceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='fecha_agregado',
        ),
    ]
